name: Build Emojis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: cargo install vtracer
      - run: bash build_font.sh
      - name: Upload Font Artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: nanoemoji-svg1/build/Font.ttf
      - name: Upload Font Artifact 2
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: nanoemoji-svg2/build/Font.ttf
      - name: Upload Font Artifact 3
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: nanoemoji-svg3/build/Font.ttf
      - name: Upload Font Artifact 4
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: nanoemoji-svg4/build/Font.ttf
      - name: Upload Font Artifact 5
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: nanoemoji-svg5/build/Font.ttf
      - name: Upload Font Artifact 6
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: nanoemoji-svg6/build/Font.ttf
      - name: Upload Font Artifact 7
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: nanoemoji-svg7/build/Font.ttf
      - name: Upload Font Artifact 8
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: nanoemoji-svg8/build/Font.ttf
      - name: Upload Font Artifact 9
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: nanoemoji-svg9/build/Font.ttf
