# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Emojis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: cargo install vtracer
    - run: bash build_font.sh
    - name: Upload Font Artifact
      uses: actions/upload-artifact@v3
      with:
          name: code-coverage-report
          path: nanoemoji/build/Font.ttf
